[workspace]
members = ["packages/*"]
default-members = ["packages/*"]
resolver = "2"
exclude = [
    "linkchecker", # linkchecker is part of the CI workflow
    "listings",    # these are intentionally distinct from the workspace
]

[workspace.dependencies]
assert_cmd = "2.0.14"
walkdir = "2.3.1"
clap = { version = "4.5.4", features = ["derive"] }
docopt = "1.1.0"
mdbook = "0.4.37"
pulldown-cmark = { version = "0.10.3", features = ["simd"] }
pulldown-cmark-to-cmark = "13.0.0"
serde = "1.0"
serde_json = "1.0"
regex = "1.3.3"
lazy_static = "1.4.0"
flate2 = "1.0.13"
tar = "0.4.26"
