[package]
name = "mdbook-trpl-listing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { workspace = true }
mdbook = { workspace = true }
pulldown-cmark = { workspace = true }
pulldown-cmark-to-cmark = { workspace = true }
serde_json = { workspace = true }
thiserror = "1.0.60"
toml = "0.8.12"
xmlparser = "0.13.6"

[dev-dependencies]
assert_cmd = { workspace = true }
