[package]
name = "mdbook-trpl-note"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
mdbook = { workspace = true }
pulldown-cmark = { version = "0.10.3", features = ["simd"] }
pulldown-cmark-to-cmark = "13.0.0"
serde_json = "1.0.116"

[dev-dependencies]
assert_cmd = "2.0.14"
